name: tests
run-name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  node-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: "Checkout out repository"

      - uses: actions/setup-node@v4
        name: "Set up Node.js"
        with:
          node-version: 21.x
          cache: npm

      - run: npm install
        name: "Install project dependencies"

      - run: npm run test
        name: "Run tests"
